       - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/html
            # 1. Force the server to match GitHub exactly (Delete local changes)
            git fetch --all
            git reset --hard origin/main
            
            # 2. Now pull (It will work 100%)
            git pull origin main
            
            # 3. Clean Install & Build
            npm ci
            npm run build
